actions:
  cache-font: fc-cache -f -v
  reload-xresources: xrdb ~/.Xresources
  vundle-refresh: vim +VundleClean! +VundleInstall +VundleInstall! +qall
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    actions:
    - vundle-refresh
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
    actions:
    - reload-xresources
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_i3status_config:
    src: config/i3status/config
    dst: ~/.config/i3status/config
  f_inconsolata-regular.ttf:
    src: fonts/Inconsolata-Regular/Inconsolata-Regular.ttf
    dst: ~/.fonts/Inconsolata-Regular/Inconsolata-Regular.ttf
    actions:
    - cache-font
  f_gdbinit:
    src: gdbinit
    dst: ~/.gdbinit
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_oh-my-zsh:
    src: oh-my-zsh
    dst: ~/.oh-my-zsh
  f_zsh_theme:
    src: zsh/marc-pygmalion.zsh-theme
    dst: ~/.oh-my-zsh/themes/marc-pygmalion.zsh-theme
profiles:
  laptop:
    include:
    - bash
    - zsh
    - vim
    - x11
    - i3
    - font
    - git
    - gdb
  work:
    include:
    - bash
    - zsh
    - vim
    - x11
    - i3
    - font
    - git
    - gdb
  dev-bash:
    include:
    - bash
    - vim
  dev-zsh:
    include:
    - zsh
    - vim

  # Packages to be used above
  bash:
    dotfiles:
    - f_bashrc
  zsh:
    dotfiles:
    - f_zshrc
    - d_oh-my-zsh
    - f_zsh_theme
  vim:
    dotfiles:
    - f_vimrc
  x11:
    dotfiles:
    - f_xresources
    - f_xinitrc
  i3:
    dotfiles:
    - f_config
    - f_i3status_config
  font:
    dotfiles:
    - f_inconsolata-regular.ttf
  git:
    dotfiles:
    - f_gitconfig
  gdb:
    dotfiles:
    - f_gdbinit
